version: '3.7'

services:

  app:
    depends_on:
      - postgresql
      - redis
    env_file: env_file
    environment: &mayan_env
      MAYAN_CELERY_BROKER_URL: redis://:${MAYAN_REDIS_PASSWORD:-mayanredispassword}@redis:6379/0
      MAYAN_CELERY_RESULT_BACKEND: redis://:${MAYAN_REDIS_PASSWORD:-mayanredispassword}@redis:6379/1
      MAYAN_DATABASES: "{'default':{'ENGINE':'django.db.backends.postgresql','NAME':'${MAYAN_DATABASE_DB:-mayan}','PASSWORD':'${MAYAN_DATABASE_PASSWORD:-mayandbpass}','USER':'${MAYAN_DATABASE_USER:-mayan}','HOST':'${MAYAN_DATABASE_HOST:-postgresql}'}}"
      MAYAN_DOCKER_WAIT: "${MAYAN_DATABASE_HOST:-postgresql}:5432 redis:6379"
      MAYAN_DOCUMENTS_LANGUAGE_CODES: '["eng", "spa"]'
      MAYAN_DOCUMENTS_LANGUAGE: 'spa'      
    image: mayanedms/mayanedms:${MAYAN_DOCKER_IMAGE_TAG:-3.5}
    networks:
      - bridge
    ports:
      - "8200:8000"
    restart: unless-stopped
    volumes:
      - ./app:/var/lib/mayan

  postgresql:
    environment:
      POSTGRES_DB: ${MAYAN_DATABASE_DB:-mayan}
      POSTGRES_PASSWORD: ${MAYAN_DATABASE_PASSWORD:-mayandbpass}
      POSTGRES_USER: ${MAYAN_DATABASE_USER:-mayan}
    image: postgres:${MAYAN_DOCKER_POSTGRES_TAG:-13.0-alpine}
    networks:
      - bridge
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    command:
      - redis-server
      - --appendonly
      - "no"
      - --databases
      - "2"
      - --maxmemory
      - "100mb"
      - --maxclients
      - "500"
      - --maxmemory-policy
      - "allkeys-lru"
      - --save
      - ""
      - --tcp-backlog
      - "256"
      - --requirepass
      - "${MAYAN_REDIS_PASSWORD:-mayanredispassword}"
    image: redis:${MAYAN_DOCKER_REDIS_TAG:-6.0-alpine}
    networks:
      - bridge
    restart: unless-stopped
    volumes:
      - ./redis:/data

networks:
  bridge:
    driver: bridge    
